import 'controller/bike_brand_name_page_controller.dart';import 'package:dos/core/app_export.dart';import 'package:dos/widgets/custom_elevated_button.dart';import 'package:dos/widgets/custom_radio_button.dart';import 'package:flutter/material.dart';import 'package:dos/presentation/bike_page_bottomsheet/bike_page_bottomsheet.dart';import 'package:dos/presentation/bike_page_bottomsheet/controller/bike_page_controller.dart';
// ignore_for_file: must_be_immutable
class BikeBrandNamePageBottomsheet extends StatelessWidget {BikeBrandNamePageBottomsheet(this.controller, {Key? key}) : super(key: key);

BikeBrandNamePageController controller;

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.all(12.h), decoration: AppDecoration.gradientTealEToTealE.copyWith(borderRadius: BorderRadiusStyle.customBorderTL32), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgRectangle6155x335, height: 155.v, width: 335.h, radius: BorderRadius.vertical(top: Radius.circular(32.h))), SizedBox(height: 13.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 32.h, right: 48.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.6, child: SizedBox(width: 87.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgEye, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_normal".tr, style: theme.textTheme.bodyLarge))]))), _buildRadioButtonSelector()]))), SizedBox(height: 16.v), _buildBrandNameSection()])); } 
/// Section Widget
Widget _buildRadioButtonSelector() { return Opacity(opacity: 0.6, child: Obx(() => CustomRadioButton(text: "lbl_ev".tr, value: "lbl_ev".tr, groupValue: controller.radioGroup.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.radioGroup.value = value;}))); } 
/// Section Widget
Widget _buildBrandNameSection() { return Container(margin: EdgeInsets.symmetric(horizontal: 8.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 16.v), decoration: AppDecoration.outlineBlack900013.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgSettingsBlack90001, height: 20.v, width: 24.h), Padding(padding: EdgeInsets.only(left: 5.h), child: Text("lbl_brand_name".tr, style: theme.textTheme.bodyMedium))]), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(left: 24.h, right: 173.h), child: Obx(() => Column(children: [CustomRadioButton(text: "lbl_yamaha".tr, value: controller.bikeBrandNamePageModelObj.value.radioList.value[0], groupValue: controller.brandName.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.bodyLargeWhiteA700, onChange: (value) {controller.brandName.value = value;}), Padding(padding: EdgeInsets.only(top: 18.v, right: 10.h), child: CustomRadioButton(text: "lbl_honda".tr, value: controller.bikeBrandNamePageModelObj.value.radioList.value[1], groupValue: controller.brandName.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.bodyLargeWhiteA700, onChange: (value) {controller.brandName.value = value;}))]))), SizedBox(height: 18.v), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(left: 27.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgContrastWhiteA700, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v), child: Text("lbl_big_wing".tr, style: CustomTextStyles.bodyLargeWhiteA700))]))), SizedBox(height: 83.v), CustomElevatedButton(width: 88.h, text: "lbl_submit".tr, onPressed: () {onTapSubmit();}, alignment: Alignment.center), SizedBox(height: 3.v)])); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [BikePageBottomsheet] widget.
///
/// The bottom sheet is controlled by the [BikePageController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapSubmit() { Get.bottomSheet(BikePageBottomsheet(Get.put(BikePageController(),),),isScrollControlled: true,); } 
 }
