import 'controller/computer_vendor_details_controller.dart';import 'package:dos/core/app_export.dart';import 'package:dos/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:dos/presentation/computer_page_bottomsheet/computer_page_bottomsheet.dart';import 'package:dos/presentation/computer_page_bottomsheet/controller/computer_page_controller.dart';class ComputerVendorDetailsScreen extends GetWidget<ComputerVendorDetailsController> {const ComputerVendorDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(color: appTheme.whiteA700, gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.teal400.withOpacity(0.91), appTheme.teal20068, appTheme.whiteA700.withOpacity(0)])), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 11.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 10.v), decoration: AppDecoration.outlineBlack90001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 15.v), onTap: () {onTapImgArrowDown();}), Padding(padding: EdgeInsets.only(left: 100.h, bottom: 11.v), child: Text("lbl_vendors".tr, style: CustomTextStyles.bodyLargeLatoWhiteA700))]), SizedBox(height: 27.v), _buildArrowDownRow(), SizedBox(height: 41.v), _buildRequestRow(), SizedBox(height: 41.v)])))))); } 
/// Section Widget
Widget _buildArrowDownRow() { return Padding(padding: EdgeInsets.only(right: 5.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse437x37, height: 37.adaptSize, width: 37.adaptSize, radius: BorderRadius.circular(18.h)), Padding(padding: EdgeInsets.only(left: 13.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_rahul_krishna".tr, style: CustomTextStyles.bodyLargeLatoBluegray900), Text("lbl_ryan_services".tr, style: CustomTextStyles.bodyLargeLatoWhiteA700)])), Spacer(), CustomElevatedButton(height: 28.v, width: 115.h, text: "lbl_request".tr, margin: EdgeInsets.only(top: 10.v), buttonStyle: CustomButtonStyles.outlineBlack, buttonTextStyle: CustomTextStyles.bodyLargeLato, onPressed: () {onTapRequest();})])); } 
/// Section Widget
Widget _buildRequestRow() { return Padding(padding: EdgeInsets.only(right: 5.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse437x37, height: 37.adaptSize, width: 37.adaptSize, radius: BorderRadius.circular(18.h), margin: EdgeInsets.only(bottom: 3.v)), Padding(padding: EdgeInsets.only(left: 13.h, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_rahul_krishna".tr, style: CustomTextStyles.bodyLargeLatoBluegray900), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_ryan_services".tr, style: CustomTextStyles.bodyLargeLatoWhiteA700))])), Spacer(), CustomElevatedButton(height: 28.v, width: 115.h, text: "lbl_request".tr, margin: EdgeInsets.only(top: 12.v), buttonStyle: CustomButtonStyles.outlineBlack, buttonTextStyle: CustomTextStyles.bodyLargeLato)])); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [ComputerPageBottomsheet] widget.
///
/// The bottom sheet is controlled by the [ComputerPageController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapImgArrowDown() { Get.bottomSheet(ComputerPageBottomsheet(Get.put(ComputerPageController(),),),isScrollControlled: true,); } 
/// Navigates to the computerRequestedPageScreen when the action is triggered.
onTapRequest() { Get.toNamed(AppRoutes.computerRequestedPageScreen, ); } 
 }
