import '../my_booking_screen/widgets/userprofilelist_item_widget.dart';import 'controller/my_booking_controller.dart';import 'models/userprofilelist_item_model.dart';import 'package:dos/core/app_export.dart';import 'package:flutter/material.dart';class MyBookingScreen extends GetWidget<MyBookingController> {const MyBookingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(color: appTheme.whiteA700, boxShadow: [BoxShadow(color: appTheme.black90001.withOpacity(0.25), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 4))], gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.teal400, appTheme.teal20068, appTheme.whiteA700.withOpacity(0)])), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 14.v), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgArrowDownBlack90001, height: 16.adaptSize, width: 16.adaptSize, alignment: Alignment.centerLeft, onTap: () {onTapImgArrowDown();}), _buildMyBookingsRow(), SizedBox(height: 12.v), _buildUserProfileList()]))))); } 
/// Section Widget
Widget _buildMyBookingsRow() { return Padding(padding: EdgeInsets.only(left: 8.h, right: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 7.v, bottom: 2.v), child: Text("lbl_my_bookings".tr, style: CustomTextStyles.titleLargeMedium22)), CustomImageView(imagePath: ImageConstant.imgPlay, height: 37.adaptSize, width: 37.adaptSize)])); } 
/// Section Widget
Widget _buildUserProfileList() { return Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 6.v);}, itemCount: controller.myBookingModelObj.value.userprofilelistItemList.value.length, itemBuilder: (context, index) {UserprofilelistItemModel model = controller.myBookingModelObj.value.userprofilelistItemList.value[index]; return UserprofilelistItemWidget(model, onTapUserProfile: () {onTapUserProfile();});}))); } 
/// Navigates to the acceptedStatusScreen when the action is triggered.
onTapUserProfile() { Get.toNamed(AppRoutes.acceptedStatusScreen); } 
/// Navigates to the profilePageScreen when the action is triggered.
onTapImgArrowDown() { Get.toNamed(AppRoutes.profilePageScreen, ); } 
 }
