import '../my_booking_screen/widgets/userprofilelist_item_widget.dart';import 'package:dos/core/app_export.dart';import 'package:flutter/material.dart';class MyBookingScreen extends StatelessWidget {const MyBookingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(color: appTheme.whiteA700, boxShadow: [BoxShadow(color: appTheme.black90001.withOpacity(0.25), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 4))], gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.teal400, appTheme.teal20068, appTheme.whiteA700.withOpacity(0)])), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 14.v), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgArrowDownBlack90001, height: 16.adaptSize, width: 16.adaptSize, alignment: Alignment.centerLeft, onTap: () {onTapImgArrowDown(context);}), _buildMyBookingsRow(context), SizedBox(height: 12.v), _buildUserProfileList(context)]))))); } 
/// Section Widget
Widget _buildMyBookingsRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 8.h, right: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 7.v, bottom: 2.v), child: Text("My bookings", style: CustomTextStyles.titleLargeMedium22)), CustomImageView(imagePath: ImageConstant.imgPlay, height: 37.adaptSize, width: 37.adaptSize)])); } 
/// Section Widget
Widget _buildUserProfileList(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 6.v);}, itemCount: 5, itemBuilder: (context, index) {return UserprofilelistItemWidget(onTapUserProfile: () {onTapUserProfile(context);});})); } 
/// Navigates to the acceptedStatusScreen when the action is triggered.
onTapUserProfile(BuildContext context) { Navigator.pushNamed(context, AppRoutes.acceptedStatusScreen); } 
/// Navigates to the profilePageScreen when the action is triggered.
onTapImgArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.profilePageScreen); } 
 }
