import 'controller/car_brand_name_page_controller.dart';import 'package:dos/core/app_export.dart';import 'package:dos/widgets/custom_elevated_button.dart';import 'package:dos/widgets/custom_radio_button.dart';import 'package:flutter/material.dart';import 'package:dos/presentation/car_page_bottomsheet/car_page_bottomsheet.dart';import 'package:dos/presentation/car_page_bottomsheet/controller/car_page_controller.dart';
// ignore_for_file: must_be_immutable
class CarBrandNamePageBottomsheet extends StatelessWidget {CarBrandNamePageBottomsheet(this.controller, {Key? key}) : super(key: key);

CarBrandNamePageController controller;

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 11.v), decoration: AppDecoration.gradientTealEToTealE.copyWith(borderRadius: BorderRadiusStyle.customBorderTL32), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgRectangle4155x335, height: 155.v, width: 335.h, radius: BorderRadius.vertical(top: Radius.circular(32.h))), SizedBox(height: 20.v), _buildRadioGroupSelector(), SizedBox(height: 17.v), _buildBrandNameSection()])); } 
/// Section Widget
Widget _buildRadioGroupSelector() { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 32.h, right: 88.h), child: Obx(() => Row(children: [CustomRadioButton(text: "lbl_normal".tr, value: controller.carBrandNamePageModelObj.value.radioList.value[0], groupValue: controller.radioGroup.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.radioGroup.value = value;}), Padding(padding: EdgeInsets.only(left: 78.h), child: CustomRadioButton(text: "lbl_ev".tr, value: controller.carBrandNamePageModelObj.value.radioList.value[1], groupValue: controller.radioGroup.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.radioGroup.value = value;}))])))); } 
/// Section Widget
Widget _buildBrandNameSection() { return Container(margin: EdgeInsets.symmetric(horizontal: 8.h), padding: EdgeInsets.symmetric(horizontal: 39.h, vertical: 15.v), decoration: AppDecoration.outlineBlack900013.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 5.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 20.v, width: 24.h), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_brand_name".tr, style: theme.textTheme.bodyMedium))])), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(right: 106.h), child: Obx(() => Column(children: [Padding(padding: EdgeInsets.only(right: 64.h), child: CustomRadioButton(text: "lbl_nexa".tr, value: controller.carBrandNamePageModelObj.value.radioList1.value[0], groupValue: controller.radioGroup1.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.bodyLargeWhiteA700, onChange: (value) {controller.radioGroup1.value = value;})), Padding(padding: EdgeInsets.only(top: 18.v), child: CustomRadioButton(text: "lbl_maruti_suzuki".tr, value: controller.carBrandNamePageModelObj.value.radioList1.value[1], groupValue: controller.radioGroup1.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.bodyLargeWhiteA700, onChange: (value) {controller.radioGroup1.value = value;})), Padding(padding: EdgeInsets.only(left: 3.h, top: 18.v, right: 67.h), child: CustomRadioButton(text: "lbl_tata".tr, value: controller.carBrandNamePageModelObj.value.radioList1.value[2], groupValue: controller.radioGroup1.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.bodyLargeWhiteA700, onChange: (value) {controller.radioGroup1.value = value;}))]))), SizedBox(height: 83.v), CustomElevatedButton(width: 88.h, text: "lbl_submit".tr, onPressed: () {onTapSubmit();}, alignment: Alignment.center), SizedBox(height: 5.v)])); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [CarPageBottomsheet] widget.
///
/// The bottom sheet is controlled by the [CarPageController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapSubmit() { Get.bottomSheet(CarPageBottomsheet(Get.put(CarPageController(),),),isScrollControlled: true,); } 
 }
